version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/spring-market-web/zip/
    overwrite: merge

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
  - location: scripts/beforeInstall.sh
    timeout: 60
    runas: ec2-user

  ApplicationStart:
  - location: scripts/deploy.sh
    timeout: 60
    runas: ec2-user