spring:
  #DB 관련
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: ng1029

  h2:
    console:
      enabled: true

  #프로필 관련
  profiles:
    include: credentials

  #JPA 설정
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #파일 업로드 관련
  servlet:
    multipart:
      max-file- size: 10MB
      max-request-size: 10MB

#AWS s3 업로드 경로 ( 상품 이미지 )
cloud:
  aws:
    region:
      auto: true
      static: ap-northeast-2
    s3:
      bucket: app-product-image
    stack:
      auto: false
    credentials:
      instanceProfile: true