spring:
  #DB 관련
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: ng1029

  h2:
    console:
      enabled: true

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #프로필 관련
  profiles:
    active: local
    include: credentials

  #파일 업로드 관련
  servlet:
    multipart:
      max-file- size: 10MB
      max-request-size: 10MB


#로깅 관련
logging:
  level:
    root: debug
  logback:
    rollingpolicy:
      clean-history-on-start:


#업로드 포트
server:
  port: 7070


#AWS s3 업로드 경로 ( 상품 이미지 )
cloud:
  aws:
    region:
      auto: true
      static: ap-northeast-2
    s3:
      bucket: app-product-image
    stack:
      auto: false
    credentials:
      instanceProfile: true


#로컬 파일 시스템 업로드 경로 ( 사용중 x )
local:
  filesystem:
    upload:
      path: C:\Users\김시호\Desktop\app이미지